version: "3.8"

services:
  backend_asset:
    container_name: backend_asset
    image: dimax94/microservice_backend_asset
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - rabbitmq

  device_entrypoint:
    container_name: device_entrypoint
    image: dimax94/microservice_device_entrypoint
    depends_on:
      - redis
      - device_evaluation
      - rabbitmq

  device_evaluation:
    container_name: device_evaluation
    image: dimax94/microservice_device_evaluation
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - redis
      - antecedent_evaluation
      - rabbitmq

  antecedent_evaluation:
    container_name: antecedent_evaluation
    image: dimax94/microservice_antecedent_evaluation
    depends_on:
      - redis
      - rule_evaluation
      - rabbitmq

  timer_evaluation:
    container_name: timer_evaluation
    image: dimax94/microservice_timer_evaluation
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - redis
      - rule_evaluation
      - rabbitmq

  laston_evaluation:
    container_name: laston_evaluation
    image: dimax94/microservice_laston_evaluation
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - redis
      - rule_evaluation
      - rabbitmq

  rule_evaluation:
    container_name: rule_evaluation
    image: dimax94/microservice_rule_evaluation
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - redis
      - consequent_evaluation
      - rabbitmq

  consequent_evaluation:
    container_name: consequent_evaluation
    image: dimax94/microservice_consequent_evaluation
    depends_on:
      - redis
      - rabbitmq

  switch_sync:
    container_name: switch_sync
    image: dimax94/microservice_switch_sync
    depends_on:
      - redis
      - rabbitmq

  rabbitmq:
    container_name: rabbitmq
    image: dimax94/rabbitmq
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    container_name: redis
    image: dimax94/redis
    ports:
      - "6379:6379"

  frontend:
    container_name: frontend
    image: dimax94/frontend
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8084:8084"

  reverse_proxy:
    container_name: reverse_proxy
    image: dimax94/reverse_proxy
    depends_on:
      - backend_asset
    ports:
      - "8081:8081"










