version: "3"
networks:
  redisnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16

services:
  redis-cluster:
    container_name: redis-cluster
    image: dimax94/redis_cluster_create
    command: redis-cli -p 7000 --cluster create 10.0.0.11:7001 10.0.0.12:7002 10.0.0.13:7003 10.0.0.14:7004 10.0.0.15:7005 10.0.0.16:7006 --cluster-replicas 1 --cluster-yes
    ports:
      - 7000:6379
    depends_on:
      - redis-1
      - redis-2
      - redis-3
      - redis-4
      - redis-5
      - redis-6
    networks:
      redisnet:
        ipv4_address: 10.0.0.2

  redis-1:
    container_name: redis-1
    image: dimax94/redis_cluster_node1
    networks:
      redisnet:
        ipv4_address: 10.0.0.11
    ports:
      - 7001:6379

  redis-2:
    container_name: redis-2
    image: dimax94/redis_cluster_node2
    networks:
      redisnet:
        ipv4_address: 10.0.0.12
    ports:
      - 7002:6379

  redis-3:
    container_name: redis-3
    image: dimax94/redis_cluster_node3
    networks:
      redisnet:
        ipv4_address: 10.0.0.13
    ports:
      - 7003:6379

  redis-4:
    container_name: redis-4
    image: dimax94/redis_cluster_node4
    networks:
      redisnet:
        ipv4_address: 10.0.0.14
    ports:
      - 7004:6379

  redis-5:
    container_name: redis-5
    image: dimax94/redis_cluster_node5
    networks:
      redisnet:
        ipv4_address: 10.0.0.15
    ports:
      - 7005:6379

  redis-6:
    container_name: redis-6
    image: dimax94/redis_cluster_node6
    networks:
      redisnet:
        ipv4_address: 10.0.0.16
    ports:
      - 7006:6379










