version: "3"

services:
  redis-cluster:
    container_name: redis-cluster
    image: dimax94/redis_cluster_create
    command: redis-cli --cluster create 192.168.1.96:7001 192.168.1.96:7002 192.168.1.96:7003 192.168.1.96:7004 192.168.1.96:7005 192.168.1.96:7006 --cluster-replicas 1 --cluster-yes
    ports:
      - 7000:6379
    depends_on:
      - redis-1
      - redis-2
      - redis-3
      - redis-4
      - redis-5
      - redis-6

  redis-1:
    container_name: redis-1
    image: dimax94/redis_cluster_node1
    ports:
      - 7001:6379

  redis-2:
    container_name: redis-2
    image: dimax94/redis_cluster_node2
    ports:
      - 7002:6379

  redis-3:
    container_name: redis-3
    image: dimax94/redis_cluster_node3
    ports:
      - 7003:6379

  redis-4:
    container_name: redis-4
    image: dimax94/redis_cluster_node4
    ports:
      - 7004:6379

  redis-5:
    container_name: redis-5
    image: dimax94/redis_cluster_node5
    ports:
      - 7005:6379

  redis-6:
    container_name: redis-6
    image: dimax94/redis_cluster_node6
    ports:
      - 7006:6379










